import { createContext, useContext, useEffect, useMemo, useState } from 'react'

const STORAGE_KEY = 'control-room-language'
export const messages = {
  en: {
    appearance: 'Appearance', language: 'Language', preferences: 'Theme and language', overview: 'Overview', tenants: 'Tenants', identity: 'Identity', scheduler: 'Scheduler', alerts: 'Alerts', auditLog: 'Audit log', gatewayLogs: 'Gateway logs', logout: 'Log out', mainNavigation: 'Main navigation',
    loading: 'Loading data…', retry: 'Try again', empty: 'No data to display.', rowsPerPage: 'Rows per page', previous: 'Previous', next: 'Next', page: 'Page', showing: 'Showing', of: 'of', closeDialog: 'Close dialog', closeNotification: 'Close notification',
    welcome: 'Welcome back', credentials: 'Use your User Management credentials.', tenantKey: 'Tenant key', username: 'Username', password: 'Password', showPassword: 'Show password', hidePassword: 'Hide password', verifying: 'Verifying…', signIn: 'Sign in to dashboard →', sessionOnly: 'Your secure session is kept in an HttpOnly cookie.', loginIntro: 'Monitor identity, schedules, alerts, and audits from one calm operations center.',
    goodSystems: 'Good systems feel quiet.', overviewIntro: 'All your operational services, summarized in one view.', gatewayConnected: 'Gateway connected', ready: 'Ready', open: 'Open →', architecture: 'Architecture at a glance', requestFlow: 'REQUEST FLOW', webDashboard: 'Web dashboard', singleEntry: 'Single entry point', backendServices: 'Backend services', domainRouting: 'Domain routing',
    refresh: 'Refresh', applyFilters: 'Apply filters', reset: 'Reset', all: 'All', yes: 'Yes', no: 'No', cancel: 'Cancel', save: 'Save', saving: 'Saving…', actions: 'Actions', delete: 'Delete', active: 'Active', disabled: 'Disabled', created: 'Created', minutes: 'minutes',
    tenantManagement: 'Tenant management', tenantIntro: 'Manage tenants and prepare their first superadmin account.', tenantList: 'Tenant list', registerTenant: 'Register tenant', tenantDirectory: 'Tenant directory', newTenant: 'New tenant', tenantInformation: 'Tenant information', tenantName: 'Tenant name', tokenLifetime: 'Access token lifetime', ownerAccount: 'Owner account', ownerUsername: 'Owner username', ownerEmail: 'Owner email', ownerPassword: 'Owner password', register: 'Register tenant', registering: 'Registering…', tenantReady: 'Tenant is ready to use',
    identityAccess: 'Identity & access', identityIntro: 'Manage who can access each service.', add: 'Add', newUser: 'New user', newRole: 'New role', newPermission: 'New permission', schedulerIntro: 'Orchestrate HTTP jobs and track every execution.', date: 'Date', fromTime: 'From time', toTime: 'To time', thresholdExceeded: 'Threshold exceeded', createHttpTask: 'Create HTTP task', createSchedule: 'Create schedule', lastTask: 'Last task',
    alertCenter: 'Alert center', alertIntro: 'Configure recipients and send messages through one trusted path.', configureRecipients: 'Configure recipients first', createAlert: 'Create alert →', creatingAlert: 'Creating alert…', dispatchNow: 'Dispatch now', safeDeliveryText: 'Only active recipients are included in the payload through the API Gateway.', useWildcard: 'Use * for global configuration', auditIntro: 'Trace important actions across the entire system.', eventExplorer: 'Event explorer', inspect: 'Inspect', eventDetail: 'Event detail', sourceSystem: 'Source system', endpoint: 'Endpoint', outcome: 'Outcome', allOutcomes: 'All outcomes', gatewayLogsIntro: 'Monitor requests and responses captured by the API Gateway.', requestExplorer: 'Request explorer', route: 'Route', method: 'Method', responseStatus: 'Response status', actor: 'Actor', path: 'Path', duration: 'Duration', requestDetail: 'Gateway request detail', scrollableTable: 'Scrollable data table',
    systemOverview: 'System overview', secureAccess: 'Secure access', centralizedService: 'Centralized service', serviceOperations: 'Service operations', dashboard: 'Dashboard', colorPalette: 'Color palette', userManagement: 'User management', immutableTrail: 'Immutable trail', requestObservability: 'Request observability', oneRoomEverySignal: 'One room. Every signal.', identityServiceDescription: 'Tenants, users, roles & permissions', schedulerServiceDescription: 'Tasks, groups & executions', alertServiceDescription: 'Create & dispatch notifications', auditServiceDescription: 'Trace every critical action',
    time: 'Time', source: 'Source', service: 'Service', action: 'Action', events: 'events', requests: 'requests', status: 'Status', type: 'Type', edit: 'Edit', inactive: 'Inactive', success: 'Success', failed: 'Failed', error: 'Error', name: 'Name', description: 'Description', resource: 'Resource', authority: 'Authority', custom: 'Custom', system: 'System', grants: 'grants',
    users: 'Users', roles: 'Roles', permissions: 'Permissions', accessDirectory: 'Access directory', selectLabel: 'Select {label}', selectAtLeastOneRole: 'Select at least one role.', noRoles: 'No roles are available.', noPermissions: 'No permissions are available.', userCreated: '{item} was created successfully.', userTenantHint: 'The user will be created in the tenant from the current login session.', systemRole: 'System role', customRole: 'Custom role', addItem: 'Add {item}', user: 'user', role: 'role', permission: 'permission', roleName: 'Role name',
    automationEngine: 'Automation engine', schedulerHistory: 'Scheduler history', schedules: 'Schedules', tasks: 'Tasks', groups: 'Groups', taskList: 'Task list', taskGroupList: 'Task group list', scheduleList: 'Schedule list', executionHistory: 'Execution history', configuration: 'Configuration', filterableHistory: 'Filterable history', groupId: 'Group ID', taskId: 'Task ID', started: 'Started', timeout: 'Timeout', threshold: 'Threshold', group: 'Group', mode: 'Mode', childGroups: 'Child groups', schedule: 'Schedule', target: 'Target', targetId: 'Target ID', nextExecution: 'Next execution', endpointUrl: 'Endpoint URL', requestBodyJson: 'Request body (JSON)', isoDuration: 'ISO-8601 duration', targetType: 'Target type', cronExpression: 'Cron expression', timezone: 'Timezone', itemCreated: '{item} was created successfully.',
    centralizedDelivery: 'Centralized delivery', emailHistory: 'Email history', composeAlert: 'Compose alert', recipientConfig: 'Recipient configuration', message: 'Message', content: 'Content', bodyType: 'Body type', senderEmail: 'Sender email', senderName: 'Sender name', replyToEmail: 'Reply-to email', priorityRange: 'Priority (1-9)', subject: 'Subject', body: 'Body', delivery: 'Delivery', channel: 'Channel', activeRecipients: 'Active recipients', configured: 'configured', idempotencyKey: 'Idempotency key', priority: 'Priority', safeDelivery: 'Safe delivery', databaseDirectory: 'Database directory', addRecipient: 'Add recipient', totalRecipients: 'Total recipients', activeDelivery: 'Active delivery', ccRecipients: 'CC recipients', bccRecipients: 'BCC recipients', deliveryHistory: 'Email delivery history', deliveryAttempts: 'Delivery attempts', result: 'Result', completed: 'Completed', recipients: 'Recipients', attempt: 'Attempt', providerId: 'Provider ID', recipient: 'Recipient', unnamed: 'Unnamed', displayName: 'Display name', emailAddress: 'Email address', recipientType: 'Recipient type', primaryRecipient: 'Primary recipient', carbonCopy: 'Carbon copy', blindCarbonCopy: 'Blind carbon copy', saveRecipient: 'Save recipient', editRecipient: 'Edit recipient', duplicateRecipient: 'This email already exists in the recipient configuration.', recipientUpdated: 'Recipient configuration was updated.', recipientAdded: 'Recipient was added.', recipientDeleted: 'Recipient was removed from the database configuration.', recipientRequired: 'Enable at least one recipient before creating an alert.', alertCreated: 'Alert was created for {count} recipient(s).', dispatchAccepted: 'The alert dispatch was accepted by the service.',
    realtimeNotifications: 'Realtime notifications', realtimeNotificationList: 'Realtime notification list', notifications: 'Notifications', clear: 'Clear', noRealtimeAlerts: 'No realtime alerts yet.', newAlert: 'New alert', realtimeConnected: 'Realtime connected', realtimeConnecting: 'Connecting realtime', realtimeDisconnected: 'Realtime disconnected', realtimeUnavailable: 'Realtime unavailable', realtimeError: 'Realtime unavailable',
    authorizedTenants: 'Authorized tenants', onboarding: 'Onboarding', tenantId: 'Tenant ID', tokenTtl: 'Token TTL', lowercaseHint: 'Lowercase letters, numbers, and hyphens; at least 3 characters.', minimumCharacters: 'At least {count} characters.', hour: 'hour', hours: 'hours', ownerSuperadmin: 'The owner account automatically receives the SUPERADMIN role in the new tenant.', whatHappensNext: 'What happens next', readyOneStep: 'Ready in one step', tenantPolicyCreated: 'The tenant and token policy are created.', standardPermissionsReady: 'Standard permissions are prepared.', ownerGetsAccess: 'The owner receives superadmin access.', tenantCreated: 'Tenant {tenant} was created successfully.', tenantLoginHint: 'Sign in using tenant key {tenant} and the newly created owner credentials.',
  },
  id: {
    appearance: 'Tampilan', language: 'Bahasa', preferences: 'Tema dan bahasa', overview: 'Ringkasan', tenants: 'Tenant', identity: 'Identitas', scheduler: 'Penjadwal', alerts: 'Alert', auditLog: 'Log audit', gatewayLogs: 'Log gateway', logout: 'Keluar', mainNavigation: 'Navigasi utama',
    loading: 'Mengambil data…', retry: 'Coba lagi', empty: 'Belum ada data untuk ditampilkan.', rowsPerPage: 'Baris per halaman', previous: 'Sebelumnya', next: 'Berikutnya', page: 'Halaman', showing: 'Menampilkan', of: 'dari', closeDialog: 'Tutup dialog', closeNotification: 'Tutup notifikasi',
    welcome: 'Selamat datang kembali', credentials: 'Gunakan kredensial User Management Anda.', tenantKey: 'Tenant key', username: 'Username', password: 'Password', showPassword: 'Tampilkan password', hidePassword: 'Sembunyikan password', verifying: 'Memverifikasi…', signIn: 'Masuk ke dashboard →', sessionOnly: 'Sesi aman disimpan dalam cookie HttpOnly.', loginIntro: 'Pantau identitas, jadwal, alert, dan audit dari satu pusat operasi yang tenang.',
    goodSystems: 'Sistem yang baik terasa tenang.', overviewIntro: 'Semua layanan operasional Anda, dirangkum dalam satu pandangan.', gatewayConnected: 'Gateway terhubung', ready: 'Siap', open: 'Buka →', architecture: 'Arsitektur sekilas', requestFlow: 'ALUR REQUEST', webDashboard: 'Dashboard web', singleEntry: 'Satu pintu masuk', backendServices: 'Layanan backend', domainRouting: 'Routing domain',
    refresh: 'Muat ulang', applyFilters: 'Terapkan filter', reset: 'Atur ulang', all: 'Semua', yes: 'Ya', no: 'Tidak', cancel: 'Batal', save: 'Simpan', saving: 'Menyimpan…', actions: 'Aksi', delete: 'Hapus', active: 'Aktif', disabled: 'Nonaktif', created: 'Dibuat', minutes: 'menit',
    tenantManagement: 'Manajemen tenant', tenantIntro: 'Kelola tenant dan siapkan akun superadmin pertamanya.', tenantList: 'Daftar tenant', registerTenant: 'Registrasi tenant', tenantDirectory: 'Direktori tenant', newTenant: 'Tenant baru', tenantInformation: 'Informasi tenant', tenantName: 'Nama tenant', tokenLifetime: 'Masa aktif access token', ownerAccount: 'Akun owner', ownerUsername: 'Username owner', ownerEmail: 'Email owner', ownerPassword: 'Password owner', register: 'Daftarkan tenant', registering: 'Mendaftarkan…', tenantReady: 'Tenant siap digunakan',
    identityAccess: 'Identitas & akses', identityIntro: 'Kelola siapa yang dapat mengakses setiap layanan.', add: 'Tambah', newUser: 'User baru', newRole: 'Role baru', newPermission: 'Permission baru', schedulerIntro: 'Orkestrasi pekerjaan HTTP dan lacak setiap eksekusi.', date: 'Tanggal', fromTime: 'Dari waktu', toTime: 'Sampai waktu', thresholdExceeded: 'Melebihi threshold', createHttpTask: 'Buat HTTP task', createSchedule: 'Buat schedule', lastTask: 'Task terakhir',
    alertCenter: 'Pusat alert', alertIntro: 'Konfigurasi penerima dan kirim pesan melalui satu jalur tepercaya.', configureRecipients: 'Konfigurasi penerima terlebih dahulu', createAlert: 'Buat alert →', creatingAlert: 'Membuat alert…', dispatchNow: 'Kirim sekarang', safeDeliveryText: 'Hanya penerima aktif yang disertakan dalam payload melalui API Gateway.', useWildcard: 'Gunakan * untuk konfigurasi global', auditIntro: 'Lacak tindakan penting di seluruh sistem.', eventExplorer: 'Penelusuran kejadian', inspect: 'Periksa', eventDetail: 'Detail kejadian', sourceSystem: 'Sistem sumber', endpoint: 'Endpoint', outcome: 'Hasil', allOutcomes: 'Semua hasil', gatewayLogsIntro: 'Pantau permintaan dan respons yang direkam oleh API Gateway.', requestExplorer: 'Penelusuran permintaan', route: 'Rute', method: 'Metode', responseStatus: 'Status respons', actor: 'Aktor', path: 'Path', duration: 'Durasi', requestDetail: 'Detail permintaan gateway', scrollableTable: 'Tabel data yang dapat digulir',
    systemOverview: 'Ringkasan sistem', secureAccess: 'Akses aman', centralizedService: 'Layanan terpusat', serviceOperations: 'Operasional layanan', dashboard: 'Dashboard', colorPalette: 'Palet warna', userManagement: 'Manajemen pengguna', immutableTrail: 'Jejak permanen', requestObservability: 'Observabilitas permintaan', oneRoomEverySignal: 'Satu ruang. Setiap sinyal.', identityServiceDescription: 'Tenant, pengguna, role & permission', schedulerServiceDescription: 'Task, grup & eksekusi', alertServiceDescription: 'Buat & kirim notifikasi', auditServiceDescription: 'Lacak setiap tindakan penting',
    time: 'Waktu', source: 'Sumber', service: 'Layanan', action: 'Aksi', events: 'kejadian', requests: 'permintaan', status: 'Status', type: 'Tipe', edit: 'Ubah', inactive: 'Tidak aktif', success: 'Berhasil', failed: 'Gagal', error: 'Kesalahan', name: 'Nama', description: 'Deskripsi', resource: 'Sumber daya', authority: 'Otoritas', custom: 'Kustom', system: 'Sistem', grants: 'izin',
    users: 'Pengguna', roles: 'Role', permissions: 'Permission', accessDirectory: 'Direktori akses', selectLabel: 'Pilih {label}', selectAtLeastOneRole: 'Pilih minimal satu role.', noRoles: 'Belum ada role yang dapat dipilih.', noPermissions: 'Belum ada permission yang dapat dipilih.', userCreated: '{item} berhasil dibuat.', userTenantHint: 'Pengguna akan dibuat pada tenant dari sesi login saat ini.', systemRole: 'Role sistem', customRole: 'Role kustom', addItem: 'Tambah {item}', user: 'pengguna', role: 'role', permission: 'permission', roleName: 'Nama role',
    automationEngine: 'Mesin otomasi', schedulerHistory: 'Riwayat penjadwal', schedules: 'Jadwal', tasks: 'Task', groups: 'Grup', taskList: 'Daftar task', taskGroupList: 'Daftar grup task', scheduleList: 'Daftar jadwal', executionHistory: 'Riwayat eksekusi', configuration: 'Konfigurasi', filterableHistory: 'Riwayat dengan filter', groupId: 'ID grup', taskId: 'ID task', started: 'Dimulai', timeout: 'Batas waktu', threshold: 'Ambang batas', group: 'Grup', mode: 'Mode', childGroups: 'Grup turunan', schedule: 'Jadwal', target: 'Target', targetId: 'ID target', nextExecution: 'Eksekusi berikutnya', endpointUrl: 'URL endpoint', requestBodyJson: 'Body permintaan (JSON)', isoDuration: 'Durasi ISO-8601', targetType: 'Tipe target', cronExpression: 'Ekspresi cron', timezone: 'Zona waktu', itemCreated: '{item} berhasil dibuat.',
    centralizedDelivery: 'Pengiriman terpusat', emailHistory: 'Riwayat email', composeAlert: 'Tulis alert', recipientConfig: 'Konfigurasi penerima', message: 'Pesan', content: 'Konten', bodyType: 'Tipe isi', senderEmail: 'Email pengirim', senderName: 'Nama pengirim', replyToEmail: 'Email balasan', priorityRange: 'Prioritas (1-9)', subject: 'Subjek', body: 'Isi pesan', delivery: 'Pengiriman', channel: 'Kanal', activeRecipients: 'Penerima aktif', configured: 'dikonfigurasi', idempotencyKey: 'Kunci idempotensi', priority: 'Prioritas', safeDelivery: 'Pengiriman aman', databaseDirectory: 'Direktori database', addRecipient: 'Tambah penerima', totalRecipients: 'Total penerima', activeDelivery: 'Pengiriman aktif', ccRecipients: 'Penerima CC', bccRecipients: 'Penerima BCC', deliveryHistory: 'Riwayat pengiriman email', deliveryAttempts: 'Percobaan pengiriman', result: 'Hasil', completed: 'Selesai', recipients: 'Penerima', attempt: 'Percobaan', providerId: 'ID penyedia', recipient: 'Penerima', unnamed: 'Tanpa nama', displayName: 'Nama tampilan', emailAddress: 'Alamat email', recipientType: 'Tipe penerima', primaryRecipient: 'Penerima utama', carbonCopy: 'Tembusan', blindCarbonCopy: 'Tembusan tersembunyi', saveRecipient: 'Simpan penerima', editRecipient: 'Ubah penerima', duplicateRecipient: 'Email tersebut sudah ada dalam konfigurasi penerima.', recipientUpdated: 'Konfigurasi penerima berhasil diperbarui.', recipientAdded: 'Penerima berhasil ditambahkan.', recipientDeleted: 'Penerima dihapus dari konfigurasi database.', recipientRequired: 'Aktifkan minimal satu penerima sebelum membuat alert.', alertCreated: 'Alert berhasil dibuat untuk {count} penerima.', dispatchAccepted: 'Pengiriman alert diterima oleh layanan.',
    realtimeNotifications: 'Notifikasi realtime', realtimeNotificationList: 'Daftar notifikasi realtime', notifications: 'Notifikasi', clear: 'Bersihkan', noRealtimeAlerts: 'Belum ada alert realtime.', newAlert: 'Alert baru', realtimeConnected: 'Realtime terhubung', realtimeConnecting: 'Menghubungkan realtime', realtimeDisconnected: 'Realtime terputus', realtimeUnavailable: 'Realtime tidak tersedia', realtimeError: 'Realtime tidak tersedia',
    authorizedTenants: 'Tenant yang diizinkan', onboarding: 'Orientasi awal', tenantId: 'ID tenant', tokenTtl: 'TTL token', lowercaseHint: 'Huruf kecil, angka, dan tanda hubung; minimal 3 karakter.', minimumCharacters: 'Minimal {count} karakter.', hour: 'jam', hours: 'jam', ownerSuperadmin: 'Akun owner otomatis memperoleh role SUPERADMIN pada tenant baru.', whatHappensNext: 'Langkah berikutnya', readyOneStep: 'Siap dalam satu langkah', tenantPolicyCreated: 'Tenant dan kebijakan token dibuat.', standardPermissionsReady: 'Permission standar disiapkan.', ownerGetsAccess: 'Owner mendapat akses superadmin.', tenantCreated: 'Tenant {tenant} berhasil dibuat.', tenantLoginHint: 'Masuk menggunakan tenant key {tenant} dan kredensial owner yang baru dibuat.',
  },
}

const LanguageContext = createContext({ language: 'en', setLanguage: () => {}, t: (key) => messages.en[key] || key })
const initialLanguage = () => window.localStorage.getItem(STORAGE_KEY) === 'id' ? 'id' : 'en'

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(initialLanguage)
  useEffect(() => { document.documentElement.lang = language; window.localStorage.setItem(STORAGE_KEY, language) }, [language])
  const value = useMemo(() => ({ language, setLanguage, t: (key, values = {}) => {
    const template = messages[language][key] || messages.en[key] || key
    return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, value), template)
  } }), [language])
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export const useLanguage = () => useContext(LanguageContext)
