import { createContext, useContext, useEffect, useMemo, useState } from 'react'

const STORAGE_KEY = 'control-room-language'
const messages = {
  en: {
    appearance: 'Appearance', language: 'Language', overview: 'Overview', tenants: 'Tenants', identity: 'Identity', scheduler: 'Scheduler', alerts: 'Alerts', auditLog: 'Audit log', gatewayLogs: 'Gateway logs', logout: 'Log out', mainNavigation: 'Main navigation',
    loading: 'Loading data…', retry: 'Try again', empty: 'No data to display.', rowsPerPage: 'Rows per page', previous: 'Previous', next: 'Next', page: 'Page', showing: 'Showing', of: 'of', closeDialog: 'Close dialog', closeNotification: 'Close notification',
    welcome: 'Welcome back', credentials: 'Use your User Management credentials.', tenantKey: 'Tenant key', username: 'Username', password: 'Password', verifying: 'Verifying…', signIn: 'Sign in to dashboard →', sessionOnly: 'Your secure session is kept in an HttpOnly cookie.', loginIntro: 'Monitor identity, schedules, alerts, and audits from one calm operations center.',
    goodSystems: 'Good systems feel quiet.', overviewIntro: 'All your operational services, summarized in one view.', gatewayConnected: 'Gateway connected', ready: 'Ready', open: 'Open →', architecture: 'Architecture at a glance', requestFlow: 'REQUEST FLOW', webDashboard: 'Web dashboard', singleEntry: 'Single entry point', backendServices: 'Backend services', domainRouting: 'Domain routing',
    refresh: 'Refresh', applyFilters: 'Apply filters', reset: 'Reset', all: 'All', yes: 'Yes', no: 'No', cancel: 'Cancel', save: 'Save', saving: 'Saving…', actions: 'Actions', delete: 'Delete', active: 'Active', disabled: 'Disabled', created: 'Created', minutes: 'minutes',
    tenantManagement: 'Tenant management', tenantIntro: 'Manage tenants and prepare their first superadmin account.', tenantList: 'Tenant list', registerTenant: 'Register tenant', tenantDirectory: 'Tenant directory', newTenant: 'New tenant', tenantInformation: 'Tenant information', tenantName: 'Tenant name', tokenLifetime: 'Access token lifetime', ownerAccount: 'Owner account', ownerUsername: 'Owner username', ownerEmail: 'Owner email', ownerPassword: 'Owner password', register: 'Register tenant', registering: 'Registering…', tenantReady: 'Tenant is ready to use',
    identityAccess: 'Identity & access', identityIntro: 'Manage who can access each service.', add: 'Add', newUser: 'New user', newRole: 'New role', newPermission: 'New permission', schedulerIntro: 'Orchestrate HTTP jobs and track every execution.', date: 'Date', fromTime: 'From time', toTime: 'To time', thresholdExceeded: 'Threshold exceeded', createHttpTask: 'Create HTTP task', createSchedule: 'Create schedule', lastTask: 'Last task',
    alertCenter: 'Alert center', alertIntro: 'Configure recipients and send messages through one trusted path.', configureRecipients: 'Configure recipients first', createAlert: 'Create alert →', creatingAlert: 'Creating alert…', dispatchNow: 'Dispatch now', safeDeliveryText: 'Only active recipients are included in the payload through the API Gateway.', useWildcard: 'Use * for global configuration', auditIntro: 'Trace important actions across the entire system.', eventExplorer: 'Event explorer', inspect: 'Inspect', eventDetail: 'Event detail', sourceSystem: 'Source system', endpoint: 'Endpoint', outcome: 'Outcome', allOutcomes: 'All outcomes', gatewayLogsIntro: 'Monitor requests and responses captured by the API Gateway.', requestExplorer: 'Request explorer', route: 'Route', method: 'Method', responseStatus: 'Response status', actor: 'Actor', path: 'Path', duration: 'Duration', requestDetail: 'Gateway request detail',
  },
  id: {
    appearance: 'Tampilan', language: 'Bahasa', overview: 'Ringkasan', tenants: 'Tenant', identity: 'Identitas', scheduler: 'Penjadwal', alerts: 'Alert', auditLog: 'Log audit', gatewayLogs: 'Log gateway', logout: 'Keluar', mainNavigation: 'Navigasi utama',
    loading: 'Mengambil data…', retry: 'Coba lagi', empty: 'Belum ada data untuk ditampilkan.', rowsPerPage: 'Baris per halaman', previous: 'Sebelumnya', next: 'Berikutnya', page: 'Halaman', showing: 'Menampilkan', of: 'dari', closeDialog: 'Tutup dialog', closeNotification: 'Tutup notifikasi',
    welcome: 'Selamat datang kembali', credentials: 'Gunakan kredensial User Management Anda.', tenantKey: 'Tenant key', username: 'Username', password: 'Password', verifying: 'Memverifikasi…', signIn: 'Masuk ke dashboard →', sessionOnly: 'Sesi aman disimpan dalam cookie HttpOnly.', loginIntro: 'Pantau identitas, jadwal, alert, dan audit dari satu pusat operasi yang tenang.',
    goodSystems: 'Sistem yang baik terasa tenang.', overviewIntro: 'Semua layanan operasional Anda, dirangkum dalam satu pandangan.', gatewayConnected: 'Gateway terhubung', ready: 'Siap', open: 'Buka →', architecture: 'Arsitektur sekilas', requestFlow: 'ALUR REQUEST', webDashboard: 'Dashboard web', singleEntry: 'Satu pintu masuk', backendServices: 'Layanan backend', domainRouting: 'Routing domain',
    refresh: 'Muat ulang', applyFilters: 'Terapkan filter', reset: 'Atur ulang', all: 'Semua', yes: 'Ya', no: 'Tidak', cancel: 'Batal', save: 'Simpan', saving: 'Menyimpan…', actions: 'Aksi', delete: 'Hapus', active: 'Aktif', disabled: 'Nonaktif', created: 'Dibuat', minutes: 'menit',
    tenantManagement: 'Manajemen tenant', tenantIntro: 'Kelola tenant dan siapkan akun superadmin pertamanya.', tenantList: 'Daftar tenant', registerTenant: 'Registrasi tenant', tenantDirectory: 'Direktori tenant', newTenant: 'Tenant baru', tenantInformation: 'Informasi tenant', tenantName: 'Nama tenant', tokenLifetime: 'Masa aktif access token', ownerAccount: 'Akun owner', ownerUsername: 'Username owner', ownerEmail: 'Email owner', ownerPassword: 'Password owner', register: 'Daftarkan tenant', registering: 'Mendaftarkan…', tenantReady: 'Tenant siap digunakan',
    identityAccess: 'Identitas & akses', identityIntro: 'Kelola siapa yang dapat mengakses setiap layanan.', add: 'Tambah', newUser: 'User baru', newRole: 'Role baru', newPermission: 'Permission baru', schedulerIntro: 'Orkestrasi pekerjaan HTTP dan lacak setiap eksekusi.', date: 'Tanggal', fromTime: 'Dari waktu', toTime: 'Sampai waktu', thresholdExceeded: 'Melebihi threshold', createHttpTask: 'Buat HTTP task', createSchedule: 'Buat schedule', lastTask: 'Task terakhir',
    alertCenter: 'Pusat alert', alertIntro: 'Konfigurasi recipient dan kirim pesan melalui satu jalur tepercaya.', configureRecipients: 'Konfigurasi recipient terlebih dahulu', createAlert: 'Buat alert →', creatingAlert: 'Membuat alert…', dispatchNow: 'Kirim sekarang', safeDeliveryText: 'Hanya recipient aktif yang disertakan dalam payload melalui API Gateway.', useWildcard: 'Gunakan * untuk konfigurasi global', auditIntro: 'Lacak tindakan penting di seluruh sistem.', eventExplorer: 'Penelusuran event', inspect: 'Periksa', eventDetail: 'Detail event', sourceSystem: 'Sistem sumber', endpoint: 'Endpoint', outcome: 'Hasil', allOutcomes: 'Semua hasil', gatewayLogsIntro: 'Pantau request dan response yang direkam oleh API Gateway.', requestExplorer: 'Penelusuran request', route: 'Route', method: 'Metode', responseStatus: 'Status response', actor: 'Aktor', path: 'Path', duration: 'Durasi', requestDetail: 'Detail request gateway',
  },
}

const LanguageContext = createContext({ language: 'en', setLanguage: () => {}, t: (key) => messages.en[key] || key })
const initialLanguage = () => window.localStorage.getItem(STORAGE_KEY) === 'id' ? 'id' : 'en'

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(initialLanguage)
  useEffect(() => { document.documentElement.lang = language; window.localStorage.setItem(STORAGE_KEY, language) }, [language])
  const value = useMemo(() => ({ language, setLanguage, t: (key) => messages[language][key] || messages.en[key] || key }), [language])
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export const useLanguage = () => useContext(LanguageContext)
