import { useState } from 'react'
import { Badge, Button, Field, Notice, Panel, useNotice } from '../components/ui'
import { alertApi } from '../services/api'

const initial = { sourceSystem: 'operations-ui', idempotencyKey: crypto.randomUUID(), correlationId: '', senderEmail: '', senderName: '', replyToEmail: '', subject: '', body: '', bodyType: 'TEXT', priority: 5, recipientEmail: '', recipientName: '' }
export default function AlertsPage() {
  const [form, setForm] = useState(initial); const [saving, setSaving] = useState(false); const [result, setResult] = useState(null); const notice = useNotice()
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { const { recipientEmail, recipientName, ...payload } = form; payload.priority = Number(payload.priority); payload.recipients = [{ type: 'TO', email: recipientEmail, displayName: recipientName }]; payload.attachments = []; payload.templateVariables = {}; const data = await alertApi.create(payload); setResult(data); notice.success('Alert berhasil dibuat dan siap dikirim.') } catch (error) { notice.fail(error.message) } finally { setSaving(false) } }
  const dispatch = async () => { try { await alertApi.dispatch(result.alertId); notice.success('Dispatch alert diterima oleh service.') } catch (error) { notice.fail(error.message) } }
  return <div className="page-stack"><Notice notice={notice.notice} onClose={notice.clear} /><section className="page-heading"><div><p className="eyebrow">CENTRALIZED DELIVERY</p><h2>Compose alert</h2><p>Buat pesan terstruktur dan kirim melalui satu jalur tepercaya.</p></div>{result && <Badge tone="success">{result.status}</Badge>}</section><div className="compose-grid"><Panel title="Message" eyebrow="CONTENT"><form id="alert-form" className="form-grid form-grid--two" onSubmit={submit}><Field label="Source system" name="sourceSystem" required value={form.sourceSystem} onChange={(e) => setForm({ ...form, sourceSystem: e.target.value })} /><Field as="select" options={['TEXT', 'HTML']} label="Body type" name="bodyType" value={form.bodyType} onChange={(e) => setForm({ ...form, bodyType: e.target.value })} /><Field label="Sender email" name="senderEmail" type="email" required value={form.senderEmail} onChange={(e) => setForm({ ...form, senderEmail: e.target.value })} /><Field label="Sender name" name="senderName" value={form.senderName} onChange={(e) => setForm({ ...form, senderName: e.target.value })} /><Field label="Recipient email" name="recipientEmail" type="email" required value={form.recipientEmail} onChange={(e) => setForm({ ...form, recipientEmail: e.target.value })} /><Field label="Recipient name" name="recipientName" value={form.recipientName} onChange={(e) => setForm({ ...form, recipientName: e.target.value })} /><Field label="Subject" name="subject" required value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })} /><Field label="Priority (1—9)" name="priority" type="number" min="1" max="9" value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })} /><div className="span-two"><Field as="textarea" label="Body" name="body" rows="9" required value={form.body} onChange={(e) => setForm({ ...form, body: e.target.value })} /></div></form></Panel><aside className="compose-aside"><Panel title="Delivery"><dl><dt>Channel</dt><dd>Email / SMTP</dd><dt>Idempotency key</dt><dd className="mono">{form.idempotencyKey.slice(0, 13)}…</dd><dt>Priority</dt><dd>{form.priority} / 9</dd></dl><Button form="alert-form" disabled={saving}>{saving ? 'Membuat alert…' : 'Create alert →'}</Button>{result && <Button variant="secondary" onClick={dispatch}>Dispatch sekarang</Button>}</Panel><div className="info-card"><strong>Safe delivery</strong><p>Gateway menambahkan identitas client dan correlation ID pada setiap request.</p></div></aside></div></div>
}
