import { useState } from 'react'
import { Badge, Button, DataTable, Field, Modal, Panel, Status } from '../components/ui'
import { useRemoteList } from '../hooks/useRemoteList'
import { auditApi } from '../services/api'

const formatDate = (date) => date ? new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium', timeStyle: 'medium' }).format(new Date(date)) : '—'
export default function AuditPage() {
  const [filters, setFilters] = useState({ limit: 50, sourceSystem: '', outcome: '' }); const [query, setQuery] = useState(filters); const [selected, setSelected] = useState(null); const [detailError, setDetailError] = useState('')
  const logs = useRemoteList((signal) => auditApi.list(Object.fromEntries(Object.entries(query).filter(([, v]) => v !== '')), signal), JSON.stringify(query))
  const inspect = async (row) => { setSelected(row); setDetailError(''); try { setSelected(await auditApi.detail(row.eventId)) } catch (error) { setDetailError(error.message) } }
  const columns = [{ key: 'occurredAt', label: 'Time', render: (r) => formatDate(r.occurredAt) }, { key: 'sourceSystem', label: 'Source' }, { key: 'action', label: 'Action' }, { key: 'actorName', label: 'Actor', render: (r) => r.actorName || r.actorId }, { key: 'outcome', label: 'Outcome', render: (r) => <Badge tone={r.outcome === 'SUCCESS' ? 'success' : 'error'}>{r.outcome}</Badge> }, { key: 'eventId', label: '', render: (r) => <Button variant="ghost" onClick={() => inspect(r)}>Inspect</Button> }]
  return <div className="page-stack"><section className="page-heading"><div><p className="eyebrow">IMMUTABLE TRAIL</p><h2>Audit log</h2><p>Telusuri tindakan penting lintas seluruh sistem.</p></div><Badge>{logs.data.length} events</Badge></section><Panel title="Event explorer" actions={<Button variant="ghost" onClick={logs.reload}>Refresh</Button>}><form className="filters" onSubmit={(e) => { e.preventDefault(); setQuery({ ...filters }) }}><Field label="Source system" name="sourceSystem" placeholder="scheduler" value={filters.sourceSystem} onChange={(e) => setFilters({ ...filters, sourceSystem: e.target.value })} /><Field as="select" label="Outcome" name="outcome" options={[{ value: '', label: 'All outcomes' }, 'SUCCESS', 'FAILURE']} value={filters.outcome} onChange={(e) => setFilters({ ...filters, outcome: e.target.value })} /><Button>Apply filters</Button></form><Status loading={logs.loading} error={logs.error} empty={!logs.data.length} onRetry={logs.reload} />{!logs.loading && !logs.error && logs.data.length > 0 && <DataTable rows={logs.data} columns={columns} rowKey="eventId" />}</Panel><Modal title="Event detail" open={Boolean(selected)} onClose={() => setSelected(null)}>{detailError && <p className="form-error">{detailError}</p>}<dl className="detail-list">{selected && Object.entries(selected).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{typeof value === 'object' ? <pre>{JSON.stringify(value, null, 2)}</pre> : String(value ?? '—')}</dd></div>)}</dl></Modal></div>
}
